In [7]:
import numpy as np

arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [5]:
my_list = [1,2,3]

my_list = my_list * 2
my_list

array = np.array([1,2,3])
array

array([1, 2, 3])

In [24]:
# Multi-dimensional indexing

array = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]],
                  [[13,14,15],[16,17,18]]])

array[0,1,2]

word = array[0,1,2] + array[0,0,0] + array[0,1,1] # array concatenation

word

np.int64(12)

In [ ]:
# Slicing

array = np.array([[1,2,3,4],
                   [5,6,7,8],
                    [9,10,11,12],
                    [13,14,15,16]])
                   

#array[::-1] # reverse the array
#array[1:-2:2] # select elements from index 1 to -2 with a step of 2
array[2,3] # select the element at row 2, column 3

np.int64(12)

In [ ]:
# Broadcasting

import numpy as np

array_1 = np.array([[0,0,0],
                   [10,10,10],
                   [20,20,20],
                   [30,30,30]])

array_2 = np.array([1,2,3])

print(array_1.shape) #(4,3)
print(array_2.shape) #( ,3) -> dimensions match plus there is a '1' . Hence cond. satisfied

#array_1 + array_2

(4, 3)
(3,)


In [ ]:
# Aggragate Fns.



In [ ]:
# Filtering

ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

adults = np.where(ages >= 18 , ages , 0) # only use 'where' clause when you need to preserve the above data otherwise use boolean filtering as its much faster

print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [ ]:
# Random Number Generation (Win + ; in Windows to open emoji panel)

import numpy as np

rng = np.random.default_rng(seed=1) # create a random number generator with a specific seed for reproducibility

print(rng.integers(low=1, high=101, size=(3,2))) # generate a 3x2 array of random integers between 1 and 100

[[48 52]
 [76 96]
 [ 4 15]]
